#!/bin/bash

set -e

if [ $# -ne 1 ]; then
cat <<USAGE
Invalid Args.

## Usage:

Build images using one of the dockerfiles

  $ $0 docker-file-path

e.g. the following commands builds an image called ruby-2.6:latest

  $ $0 Dockerfile.ruby-2.6

USAGE
  exit
fi


dockerfile="$1" # => Dockerfile.ruby-2.6
image_name="${dockerfile//Dockerfile./}" # => ruby-2.6
image_tag="$(git rev-parse --short HEAD)" # => 69d0ae3

echo "Building a docker image '$image_name:$image_tag' using the dockerfile at $dockerfile"
docker build --file "$dockerfile" --tag "$image_name:$image_tag" .
